swe574/apps/learning_space/urls.py
from django.urls import path
from .views import *
from coLearn.views import explore_view
from quiz.views import *


app_name = 'learning_space'

urlpatterns = [
    path('', explore_view, name='explore_view'),
    path('create/', learning_space_create_view, name='learning-space-create'),
    path('<int:learning_space_id>/', learning_space_view, name='learning_space_view'),
    path('<int:learning_space_id>/edit/', learning_space_edit_view, name='learning-space-edit'),
    path('<int:learning_space_id>/question/<int:question_id>', question_view, name='question'),
    path('<int:learning_space_id>/question/create', question_create_view, name='question-create'),
    path('mylearningspaces/', my_learning_spaces_view, name='my_learning_spaces_view'),
    path('<int:learning_space_id>/quiz/create', create_quiz, name='quiz-create'),
    path('<int:learning_space_id>/quiz/<int:quiz_id>/edit', quiz_detail, name='quiz-create'),
    path('<int:learning_space_id>/quiz/<int:quiz_id>', quiz_detail, name='quiz-create-question'),
    path('<int:learning_space_id>/quiz/<int:quiz_id>/create_question', create_quiz_question , name= 'create_quiz_question'),
    path('<int:learning_space_id>/add_tags/', add_tags_view, name='add_tags_view'),
    path('<int:learning_space_id>/remove_tags/', remove_tags_view, name='remove_tags_view')
]

swe574/swe573/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

from coLearn.views import (
    learning_space_create_view,
    learning_space_edit_view,
    learning_space_view,
    explore_view,
    sign_up_view,
    sign_in_view,
    profile_view,
    profile_edit_view,
    logout_view,
    question_view,
    question_create_view,
    my_learning_spaces_view,
    search_view
)

urlpatterns = [
    path('', explore_view, name='explore'),
    path('explore/', explore_view, name='explore'),
    path('signup/', sign_up_view, name='sign-up'),
    path('signin/', sign_in_view, name='sign-in'),
    path('logout/', logout_view, name='logout'),
    path('user/<int:user_id>/', profile_view, name='user-profile'),
    path('user/<int:user_id>/edit', profile_edit_view, name='user-profile-edit'),
    path('learningspace/create/', learning_space_create_view, name='learning-space-create'),
    path('learningspace/<int:learning_space_id>/', learning_space_view, name='learning-space'),
    path('learningspace/<int:learning_space_id>/edit/', learning_space_edit_view, name='learning-space-edit'),
    path('learningspace/<int:learning_space_id>/question/<int:question_id>', question_view, name='question'),
    path('learningspace/<int:learning_space_id>/question/create', question_create_view, name='question-create'),
    path('mylearningspaces/', my_learning_spaces_view, name='my-learning-spaces'),
    path('search/', search_view, name='search'),
    path('admin/', admin.site.urls),
]

# If DEBUG is true, the url mapping for the media files
# is appended to the urlpatterns. By doing so, media files
# are accessible during local development. 
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

swe574/swe574/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from tags.views import get_wikidata, create_tag_view, create_tag_form, get_tags_from_db, add_tag_to_space,remove_tag_from_space
from coLearn.views import (
    explore_view,
    sign_up_view,
    sign_in_view,
    profile_view,
    profile_edit_view,
    logout_view,
    search_view
)

urlpatterns = [
    path('', explore_view, name='explore'),
    path('explore/', explore_view, name='explore'),
    path('signup/', sign_up_view, name='sign-up'),
    path('signin/', sign_in_view, name='sign-in'),
    path('logout/', logout_view, name='logout'),
    path('user/<int:user_id>/', profile_view, name='user-profile'),
    path('user/<int:user_id>/edit', profile_edit_view, name='user-profile-edit'),

    path('search/', search_view, name='search'),
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    path('learningspace/', include('learning_space.urls'), name='learning-space'),
    
    path('api/', include('api.urls')),
    path('annotations/', include('annotation.urls'), name='annotation'),

    path('get_wikidata/<str:search_query>', get_wikidata, name='get_wikidata'),
    path('create_tag/', create_tag_view, name='create_tag_view'),
    path('create_tag_form/', create_tag_form, name='create_tag_form'),
    path('get_tags_from_db/<str:search_query>', get_tags_from_db, name='get_tags_from_db'),
    path('add_tag_to_space/', add_tag_to_space, name='add_tag_to_space'),
    path('remove_tag_from_space/', remove_tag_from_space, name='remove_tag_from_space'),

]

# If DEBUG is true, the url mapping for the media files
# is appended to the urlpatterns. By doing so, media files
# are accessible during local development. 
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

swe574/apps/learning_space/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models

# Create your models here.

# Model used for Learning Spaces.
from coLearn.models import CoLearnUser
from quiz.models import Quiz


# Answer sent to a Question.
from tags.models import Tag


class Answer(models.Model):
    sender = models.ForeignKey(CoLearnUser, on_delete=models.CASCADE, related_name='answer_sender')
    content = models.CharField(max_length=500, blank=True)


# Model used for Questions.
class Question(models.Model):
    question_title = models.CharField(max_length=100)
    author = models.ForeignKey(CoLearnUser, on_delete=models.PROTECT)
    question_content = models.CharField(max_length=500)
    answers = models.ManyToManyField(Answer, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)


class LearningSpace(models.Model):
    overview = models.CharField(max_length=1000)
    thumbnail = models.FileField(blank=True)
    prerequisites = ArrayField(models.CharField(max_length=100), blank=True, null=True, default=list)
    title = models.CharField(max_length=100)
    keywords = ArrayField(models.CharField(max_length=100), blank=True, null=True, default=list)
    subscribers = models.ManyToManyField(CoLearnUser, blank=True)
    questions = models.ManyToManyField(Question, blank=True)
    quizzes = models.ManyToManyField(Quiz, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag, related_name="learning_space_of_the_tags", blank=True)

swe574/apps/learning_space/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

# Create your views here.
# Learning Space views.
from learning_space.form import LearningSpaceCreateForm, LearningSpaceEditForm, AnswerForm, QuestionForm
from coLearn.models import CoLearnUser
from learning_space.models import LearningSpace, Question, Answer
from tags.models import Tag


def learning_space_view(request, learning_space_id):
    learningSpace = LearningSpace.objects.get(pk=learning_space_id)

    # Obtain quizzes and questions.
    quizzes = learningSpace.quizzes.all()
    questions = learningSpace.questions.all()

    # Obtain the subscribers using the LearningSpace model.
    subscribers = learningSpace.subscribers.all()

    user_subscribed = False

    for s in subscribers:
        if s.user.id == request.user.id:
            user_subscribed = True

    user_authenticated = False

    user_id = None

    # If there is a POST request, subscribe/unsubscribe the user.
    if request.POST:
        coLearnUser = CoLearnUser.objects.get(pk=request.user.id)
        if user_subscribed:
            learningSpace.subscribers.remove(coLearnUser)
            learningSpace.save()
        else:
            learningSpace.subscribers.add(coLearnUser)
            learningSpace.save()

        return redirect('/learningspace/%d' % learning_space_id)

    if request.user.is_authenticated:
        user_authenticated = True
        user_id = request.user.id

    relatedSpaces = LearningSpace.objects.filter(keywords__overlap=learningSpace.keywords)

    activity_quizzes = []

    for activity_quiz in quizzes.order_by('-published_date')[:5]:
        quiz_author = activity_quiz.author.user
        quiz_date = activity_quiz.published_date.date()
        temp_tuple = (quiz_author, quiz_date)
        activity_quizzes.append(temp_tuple)

    activity_questions = []

    for activity_question in questions.order_by('-date_created')[:5]:
        question_author = activity_question.author.user
        question_date = activity_question.date_created.date()
        temp_tuple = (question_author, question_date)
        activity_questions.append(temp_tuple)

    context = {
        'title': learningSpace.title,
        'overview': learningSpace.overview,
        'prerequisites': learningSpace.prerequisites,
        'id': learningSpace.id,
        'quizzes': quizzes,
        'questions': questions,
        'subscribers': subscribers,
        'related_spaces': relatedSpaces,
        'user_authenticated': user_authenticated,
        'user_id': user_id,
        'user_subscribed': user_subscribed,
        'activity_quizzes': activity_quizzes,
        'activity_questions': activity_questions,
        'tags': Tag.objects.filter(learning_space_of_the_tags=learningSpace)
    }

    return render(request, 'learningSpace/learning_space.html', context)


@login_required
def learning_space_create_view(request):
    if request.method == "POST":
        form = LearningSpaceCreateForm(request.POST, request.FILES or None)
        if form.is_valid():
            space_created = LearningSpace.objects.create(**form.cleaned_data)
            if (space_created):
                return redirect('/learningspace/%d' % space_created.id)
    else:
        user_id = None

        if request.user.is_authenticated:
            user_authenticated = True
            user_id = request.user.id

        context = {'user_authenticated': user_authenticated, 'user_id': user_id}
        return render(request, 'learningSpace/learning_space_create.html', context)


@login_required
def learning_space_edit_view(request, learning_space_id):
    learningSpace = LearningSpace.objects.get(pk=learning_space_id)
    if request.method == "POST":
        form = LearningSpaceEditForm(request.POST, request.FILES or None)
        if form.is_valid():
            result = LearningSpace.objects.filter(pk=learning_space_id).update(**form.cleaned_data)
            if (result):
                return redirect('/learningspace/%d' % learning_space_id)

    user_authenticated = False
    user_id = None

    if request.user.is_authenticated:
        user_authenticated = True
        user_id = request.user.id

    context = {
        'title': learningSpace.title,
        'overview': learningSpace.overview,
        'prerequisites': learningSpace.prerequisites,
        'keywords': learningSpace.keywords,
        'id': learningSpace.id,
        'user_authenticated': user_authenticated,
        'user_id': user_id
    }

    return render(request, 'learningSpace/learning_space_edit.html', context)


# Questions views.

@login_required
def question_view(request, learning_space_id, question_id):
    question = Question.objects.get(pk=question_id)
    answers = question.answers.all()
    
    user_authenticated = False
    user_id = None

    if request.user.is_authenticated:
        user_authenticated = True
        user_id = request.user.id

    answerForm = AnswerForm(request.POST or None)
    if (answerForm.is_valid()):
        coLearnUser = CoLearnUser.objects.get(pk=request.user.id)
        answer = Answer.objects.create(sender=coLearnUser, content=answerForm.cleaned_data.get('content'))
        question.answers.add(answer)

        return redirect('/learningspace/%d/question/%d' % (learning_space_id, question_id))

    context = {
        'learning_space_id': learning_space_id,
        'question_id': question_id,
        'question': question,
        'answers': answers,
        'user_authenticated': user_authenticated,
        'user_id': user_id
    }

    return render(request, 'question/question.html', context)


@login_required
def question_create_view(request, learning_space_id):
    questionForm = QuestionForm(request.POST or None)
    if (questionForm.is_valid()):
        coLearnUser = CoLearnUser.objects.get(pk=request.user.id)
        question = Question.objects.create(author=coLearnUser,
                                           question_title=questionForm.cleaned_data.get('question_title'),
                                           question_content=questionForm.cleaned_data.get('question_content'))
        learningSpace = LearningSpace.objects.get(pk=learning_space_id)
        learningSpace.questions.add(question)
        learningSpace.save()

        return redirect('/learningspace/%d/question/%d' % (learning_space_id, question.id))
    user_authenticated = False

    user_id = None

    if request.user.is_authenticated:
        user_authenticated = True
        user_id = request.user.id

    context = {'learning_space_id': learning_space_id, 'user_authenticated': user_authenticated, 'user_id': user_id}
    return render(request, 'question/question_create.html', context)


# MyLearningSpaces views.

def my_learning_spaces_view(request):
    coLearnUser = CoLearnUser.objects.get(id=request.user.id)
    myLearningSpaces = LearningSpace.objects.filter(subscribers=coLearnUser)

    user_authenticated = False
    user_id = None

    if request.user.is_authenticated:
        user_authenticated = True
        user_id = request.user.id

    context = {
        'my_learning_spaces': myLearningSpaces,
        'user_authenticated': user_authenticated,
        'user_id': user_id
    }

    return render(request, 'myLearningSpaces/myLearningSpaces.html', context)


@login_required
def add_tags_view(request, learning_space_id):
    return render(request, 'tags/add_tags.html', {"learning_space_id": learning_space_id})


@login_required
def remove_tags_view(request, learning_space_id):
    context = {
        "learning_space_id": learning_space_id,
        "tags": Tag.objects.filter(learning_space_of_the_tags=learning_space_id)
    }
    return render(request, 'tags/remove_tags.html', context)

swe574/templates/learningSpace/learning_space.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1, shrink-to-fit=no"
		/>
		<meta
			name="description"
			content="swe 573 projet, co-learn web application"
		/>
		<meta name="author" content="onur demirkale" />

		<title>Co-Learn</title>

		<!-- Bootstrap CSS -->
		<link
			rel="stylesheet"
			href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
			integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
			crossorigin="anonymous"
		/>
	</head>
	<body>
		<!-- Navbar -->
		{% if user_authenticated %} {%include 'navbar_auth.html'%} {% else %}
		{%include 'navbar_unauth.html'%} {% endif %}
		<!-- Navbar End -->

		<div class="jumbotron p-3 p-md-5 rounded">
			<div class="col-md-6 px-0">
				<h1>{{title}}</h1>
			</div>
		</div>

		<!-- Main container -->
		<main role="main" class="container">
			<div class="row">
				<div class="col-md-8">
					<div>
						<!-- Overview block -->
						<div class="card mb-4 box-shadow">
							<div
								class="card-header d-flex justify-content-between align-items-center"
							>
								<h4 class="my-0 font-weight-normal">Overview</h4>
								{% if user_authenticated %} {% if user_subscribed %}
								<div class="ml-auto">
									<form
										id="subscribe-form"
										method="POST"
										action="."
										enctype="multipart/form-data"
									>
										{% csrf_token %}
										<button
											form="subscribe-form"
											type="submit"
											class="btn btn-md ml-auto btn-success"
										>
											Subscribed
										</button>
									</form>
								</div>
								{% else %}
								<div class="ml-auto">
									<form
										id="subscribe-form"
										method="POST"
										action="."
										enctype="multipart/form-data"
									>
										{% csrf_token %}
										<button
											form="subscribe-form"
											type="submit"
											class="btn btn-md ml-auto btn-outline-success"
										>
											Subscribe
										</button>
									</form>
								</div>
								{% endif %}
								<br />&nbsp&nbsp<br />
								<a
									class="btn btn-md btn-outline-primary"
									href="/learningspace/{{id}}/edit"
									>Edit</a
								>
								{% endif %}
							</div>
							<div class="card-body">{{overview}}</div>
						</div>
						<!-- Prerequisites block -->
						<div class="card mb-4 box-shadow">
							<div
								class="card-header d-flex justify-content-between align-items-center"
							>
								<h4 class="my-0 font-weight-normal">Prerequisites</h4>
							</div>
							<div class="card-body">
								<ul>
									{% if prerequisites %} {% for p in prerequisites %}
									<li>{{p}}</li>
									{% endfor %}{% endif %}
								</ul>
							</div>
						</div>
						<!-- Questions block -->
						<div class="card mb-4 box-shadow">
							<div
								class="card-header d-flex justify-content-between align-items-center"
							>
								<h4 class="my-0 font-weight-normal">Questions</h4>
								{% if user_authenticated %}
								<a
									class="btn btn-sm btn-outline-secondary"
									href="/learningspace/{{id}}/question/create"
									>Create Question</a
								>
								{% endif %}
							</div>
							<div class="card-body">
								<ul class="list-group mb-3">
									{% if questions %} {% for q in questions %}
									<li
										class="list-group-item d-flex justify-content-between lh-condensed"
									>
										<div>
											<h6 class="my-0">
												<a href="question/{{q.id}}">{{q.question_title}}</a>
											</h6>
											<small class="text-muted"
												>Posted by: {{q.author.user.username}}</small
											>
										</div>
										<span class="text-muted">Created: {{q.date_created}}</span>
									</li>
									{% endfor %}{% endif %}
								</ul>
							</div>
						</div>
						<!-- Questions block end -->
						<!-- Quizzes block -->
						<div class="card mb-4 box-shadow">
							<div
								class="card-header d-flex justify-content-between align-items-center"
							>
								<h4 class="my-0 font-weight-normal">Quizzes</h4>
								{% if user_authenticated %}
								<a
									class="btn btn-sm btn-outline-secondary"
									href="/learningspace/{{id}}/quiz/create"
									>Create Quiz</a
								>
								{% endif %}
							</div>
							<div class="card-body">
								<ul class="list-group mb-3">
									{% if quizzes %} {% for quiz in quizzes %}
									<li
										class="list-group-item d-flex justify-content-between lh-condensed"
									>
										<div>
											<h6 class="my-0"><a href="quiz/{{quiz.id}}">{{quiz.title}}</a></h6>
											<small class="text-muted"
												>Posted by: {{quiz.author.user.username}}</small
											>
										</div>
										<span class="text-muted">Created: {{quiz.published_date}}</span>
									</li>
									{% endfor %}{% endif %}
								</ul>
							</div>
						</div>
						<!-- Quizzes block end -->
					</div>
				</div>

				<!-- Sidebar -->
				{%include 'learningSpace/sidebar.html'%}
				<!-- Sidebar end -->
			</div>
		</main>
		<!-- Main container -->

		<!-- Footer -->
		{%include 'footer.html'%}
		<!-- Footer end-->
	</body>

swe574/templates/learningSpace/learning_space_create.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1, shrink-to-fit=no"
		/>
		<meta
			name="description"
			content="swe 573 projet, co-learn web application"
		/>
		<meta name="author" content="onur demirkale" />

		<title>Co-Learn</title>

		<!-- Bootstrap CSS -->
		<link
			rel="stylesheet"
			href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
			integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
			crossorigin="anonymous"
		/>
	</head>
	<body class="bg-light">
		<!-- Navbar -->
		{%include 'navbar_auth.html'%}
		<!-- Navbar End -->
		<div class="container">
			<div class="py-5 text-center">
				<h2>Create Learning Space</h2>
			</div>
			<div class="flex-row justify-content-center d-flex">
				<form method="POST" action="." class="needs-validation" enctype="multipart/form-data" novalidate>
					{% csrf_token %}
					<div class="form-group">
						<label>Title</label>
						<input
							type="text"
							name="title"
							class="form-control"
							placeholder="Title"
							required
						/>
						<div class="invalid-feedback">Please provide a title.</div>
					</div>

					<div class="form-group">
						<label>Overview</label>
						<textarea
							class="form-control"
							name="overview"
							rows="3"
							required
						></textarea>
						<div class="invalid-feedback">Please provide an overview.</div>
					</div>

					<div class="form-group">
						<label>Prerequisites</label>
						<input
							type="text"
							name="prerequisites"
							class="form-control"
							placeholder="Prerequisite 1, Prerequisite 2..."
						/>
					</div>

					<div class="form-group">
						<labelf>Keywords</label>
						<input
							type="text"
							name="keywords"
							class="form-control"
							placeholder="Keyword 1, Keyword 2..."
						/>
					</div>

					<div class="form-group">
						<div class="custom-file">
							<input
								type="file"
								name="thumbnail"
								accept="image/png, image/gif, image/jpeg"
								class="custom-file-input"
								required
							/>
							<label class="custom-file-label"
								>Choose a thumbnail...</label
							>
							<div class="invalid-feedback">Invalid thumbnail.</div>
						</div>
					</div>
					<div class="form-group row d-flex justify-content-center">
						<div class="text-center form-group">
							<button class="btn btn-primary" type="submit">Create</button>
						</div>
						<div>&nbsp;&nbsp;&nbsp;</div>
						<div>
							<a class="btn btn-secondary" href="/explore"
								>Cancel</a
							>
						</div>
					</div>
				</form>
			</div>
		</div>
		<!-- Footer -->
		{%include 'footer.html'%}
		<!-- Footer end-->
	</body>
</html>

<!-- JavaScript for disabling form submissions if there are invalid fields -->
<script>
	(function () {
		'use strict';
		window.addEventListener(
			'load',
			function () {
				// Fetch all the forms we want to apply custom Bootstrap validation styles to
				var forms = document.getElementsByClassName('needs-validation');
				// Loop over them and prevent submission
				var validation = Array.prototype.filter.call(forms, function (form) {
					form.addEventListener(
						'submit',
						function (event) {
							if (form.checkValidity() === false) {
								event.preventDefault();
								event.stopPropagation();
							}
							form.classList.add('was-validated');
						},
						false
					);
				});
			},
			false
		);
	})();
</script>
<!-- JavaScript End -->

swe574/templates/learningSpace/learning_space_edit.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1, shrink-to-fit=no"
		/>
		<meta
			name="description"
			content="swe 573 projet, co-learn web application"
		/>
		<meta name="author" content="onur demirkale" />

		<title>Co-Learn</title>

		<!-- Bootstrap CSS -->
		<link
			rel="stylesheet"
			href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
			integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
			crossorigin="anonymous"
		/>
	</head>
	<body class="bg-light">
		<!-- Navbar -->
		{%include 'navbar_auth.html'%}
		<!-- Navbar End -->
		<div class="container">
			<div class="py-5 text-center">
				<h2>Edit Learning Space</h2>
			</div>
			<div class="flex-row justify-content-center d-flex">
				<form method="POST" action="." enctype="multipart/form-data" class="needs-validation" novalidate>
					{% csrf_token %}
					<div class="form-group">
						<div>
							<label>Title</label>
							<input
								type="text"
								name="title"
								class="form-control"
								placeholder="Title"
								value="{{title}}"
								required
							/>
							<div class="invalid-feedback">Please provide a title.</div>
						</div>
					</div>

					<div class="form-group">
						<div>
							<label>Overview</label>
							<textarea class="form-control" rows="3" name="overview" required>
{{overview}}</textarea
							>
							<div class="invalid-feedback">Please provide an overview.</div>
						</div>
					</div>

					<div class="form-group">
						<div>
							<label>Prerequisites</label>
							<input
								type="text"
								name="prerequisites"
								class="form-control"
								value="{{ prerequisites|join:', ' }}"
								placeholder="Prerequisite 1, Prerequisite 2..."
							/>
						</div>
					</div>

					<div class="form-group">
						<div>
							<label>Keywords</label>
							<input
								type="text"
								name="keywords"
								class="form-control"
								placeholder="Keyword 1, Keyword 2..."
								value="{{ keywords|join:', ' }}"
							></input>
						</div>
					</div>

					<div class="form-group row d-flex justify-content-center">
						<div>
							<button class="btn btn-primary" type="submit">Save</button>
						</div>
						<div>&nbsp;&nbsp;&nbsp;</div>
						<div>
							<a class="btn btn-secondary" href="/learningspace/{{id}}"
								>Cancel</a
							>
						</div>
					</div>
				</form>
			</div>
		</div>
		<!-- Footer -->
		{%include 'footer.html'%}
		<!-- Footer end-->
	</body>
</html>

<!-- JavaScript for disabling form submissions if there are invalid fields -->
<script>
	(function () {
		'use strict';
		window.addEventListener(
			'load',
			function () {
				// Fetch all the forms we want to apply custom Bootstrap validation styles to
				var forms = document.getElementsByClassName('needs-validation');
				// Loop over them and prevent submission
				var validation = Array.prototype.filter.call(forms, function (form) {
					form.addEventListener(
						'submit',
						function (event) {
							if (form.checkValidity() === false) {
								event.preventDefault();
								event.stopPropagation();
							}
							form.classList.add('was-validated');
						},
						false
					);
				});
			},
			false
		);
	})();
</script>
<!-- JavaScript End -->

swe574/templates/learningSpace/sidebar.html
<aside class="col-md-4 blog-sidebar">
    <div class="p-3 mb-3 bg-light rounded">
        <h4>Users</h4>
        <ol class="list-unstyled mb-0">
            <!-- User List -->
            <li>
                <ul>
                    {% if subscribers %} {% for s in subscribers %}
                        <li>
                            <a href="{% url 'user-profile' s.user.id %}">{{ s.user.username }}</a>
                        </li>
                    {% endfor %}{% endif %}
                </ul>
            </li>
            <!-- User List End-->
        </ol>
    </div>

    <div class="p-3 mb-3 bg-light rounded">
        <h4>Related Spaces</h4>
        <ol class="list-unstyled mb-0">
            <!-- Related Spaces List -->
            <ul>
                {% if related_spaces %} {% for r in related_spaces %}
                    <li>
                        <a href="{% url "learning_space:learning_space_view" r.id %}">{{ r.title }}</a>
                    </li>
                {% endfor %}{% endif %}
            </ul>
            <!-- Related Spaces List End-->
        </ol>
    </div>

    <div class="p-3 mb-3 bg-light rounded">
        <h4>Learner Activities</h4>
        <ol class="list-unstyled mb-0">
            <!-- Learner Activity List -->
            <ul>
                {% if activity_questions %} {% for question in activity_questions %}
                    <li>
                        <a href="{% url "user-profile" question.0.id %}">{{ question.0.username }} </a> posted a
                        question at {{ question.1 }}
                    </li>
                {% endfor %}{% endif %}

                {% if activity_quizzes %} {% for quiz in activity_quizzes %}
                    <li>
                        <a href="{% url "user-profile" quiz.0.id %}">{{ quiz.0.username }} </a> created a quiz
                        at {{ quiz.1 }}
                    </li>
                {% endfor %}{% endif %}
            </ul>
            <!-- Learner Activity List End-->
        </ol>
    </div>

    <div class="p-3 mb-3 bg-light rounded">
        <h4>Add Tags</h4>
        <ol class="list-unstyled mb-0">
            <!-- Tags List -->
            <ul>
                {% if tags %} {% for tag in tags %}
                    <li>
                        {{ tag.name | title }}
                    </li>
                {% endfor %}{% endif %}


            </ul>

            <!-- Tags List End-->
        </ol>
        <a href="/learningspace/{{ id }}/add_tags/" class="btn btn-md ml-auto btn-success">Add Tag</a>
        <a href="/learningspace/{{ id }}/remove_tags/" class="btn btn-md ml-auto btn-success">Remove Tag</a>

    </div>

</aside>